name: build
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm install
        working-directory: desktop-app
      - run: npm run dist
        working-directory: desktop-app
      - uses: actions/upload-artifact@v4
        with: { name: CreoveyaSetup, path: desktop-app/dist/*.exe }